name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the `main` branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker Buildx (to use advanced features of Docker)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers for faster builds
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Log into Docker Hub
    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t rajaproxima/nodejs-docker-app .

    # Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push rajaproxima/nodejs-docker-app:latest

    # SSH into your server and deploy the Docker container (assuming you have SSH access set up)
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          docker pull rajaproxima/nodejs-docker-app:latest
          docker stop nodejs-docker-app || true
          docker rm nodejs-docker-app || true
          docker run -d -p 3003:3003 --name nodejs-docker-app rajaproxima/nodejs-docker-app:latest
